version: '3.8'
services:

  kafka:
    container_name: pelican-kafka
    image: tokensmith/kafka
    build:
      context: .
      dockerfile: docker/kafka/Dockerfile

  zookeeper:
    container_name: pelican-zookeeper
    image: tokensmith/zookeeper
    build:
      context: docker/zookeeper
      dockerfile: Dockerfile
    ports:
      - 2181:2181

  kafka-broker:
    container_name: pelican-kafka-broker
    image: tokensmith/kafka-broker
    depends_on:
      - zookeeper
    build:
      context: docker/kafka-broker
      dockerfile: Dockerfile
    ports:
      - 9092:9092
      - 29092:29092