version: '3'
services:

  kafka:
    container_name: kafka
    image: rs/kafka
    build:
      context: .
      dockerfile: docker/kafka/Dockerfile

  zookeeper:
    container_name: zookeeper
    image: rs/zookeeper
    build:
      context: docker/zookeeper
      dockerfile: Dockerfile
    ports:
      - 2181:2181

  kafka-broker:
    container_name: kafka-broker
    image: rs/kafka-broker
    depends_on:
      - zookeeper
    build:
      context: docker/kafka-broker
      dockerfile: Dockerfile
    ports:
      - 9092:9092
      - 29092:29092